apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigned-{{ .Values.env.name }}"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.env.name }}-ca"
  namespace: {{ .Values.env.namespace.field }}
spec:
  commonName: "{{ .Values.env.name }}-ca"
  isCA: true
  duration: "43800h"
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: "selfsigned-{{ .Values.env.name }}"
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: "{{ .Values.env.name }}-ca"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  annotations:
  name: "issuer-{{ .Values.env.name }}"
  namespace: {{ .Values.env.namespace.field }}
spec:
  ca:
    secretName: "{{ .Values.env.name }}-ca"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.env.name }}-certificate"
  namespace: {{ .Values.env.namespace.field }}
spec:
  secretName: "{{ .Values.env.name }}-certs"
  dnsNames:
  - "{{ .Values.env.service }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.field }}"
  - "{{ .Values.env.service }}.{{ .Values.env.namespace.field }}.svc"
  issuerRef:
    name: "issuer-{{ .Values.env.name }}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ .Values.env.namespace.field }}  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ .Values.env.namespace.compute }} # Control auto-reflection namespaces
