{{- if not .Values.irsa_client_sidecar.enabled -}}
apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: {{ .Values.env.name }}-sidecar
  namespace: {{.Values.env.namespace.platform}}
rules:
- labelSelectors:
  - "dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)"
  matchBuilds: false
  modifyLabel:
    key: dominodatalab.com/irsa-workload-type
    value: edge-workload
- labelSelectors:
  - "app.kubernetes.io/name in (spark,ray,dask)"
  - "app.kubernetes.io/component==worker"
  matchBuilds: false
  modifyLabel:
    key: dominodatalab.com/irsa-workload-type
    value: cluster-worker
- labelSelectors:
  - "app.kubernetes.io/name in (spark,ray,dask)"
  - "app.kubernetes.io/component==head"
  matchBuilds: false
  modifyLabel:
    key: dominodatalab.com/irsa-workload-type
    value: cluster-master

- labelSelectors:
  - "dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)"
  insertVolumes:
  - name: irsa-logs
    emptyDir:
      sizeLimit: 1000Mi
  - name: aws-config-file
    emptyDir:
      sizeLimit: 500Mi
  - name: podinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
  - name: aws-user-token
    projected:
      defaultMode: 422
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 86400
          audience: sts.amazonaws.com
  modifySecurityContext:
    context:
      fsGroup: 12574
- labelSelectors:
  - "dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)"
  insertVolumeMounts:
    volumeMounts:
    - name: aws-config-file
      mountPath: /var/run/.aws
    - name: aws-user-token
      mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount/
      readOnly: true
    - name: irsa-logs
      mountPath: /var/log/irsa
    - name: podinfo
      mountPath: /var/run/podinfo
      readOnly: true
  modifyEnv:
    env:
    - name: POD_INFO_PATH
      value: /var/run/podinfo/labels
    - name: DOMINO_API_PROXY
      value: http://localhost:8899
    - name: DOMINO_API_PROXY_PORT
      value: "8899"
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    - name: AWS_CONFIG_FILE
      value: /var/run/.aws/config
    - name: DOMINO_IRSA_ENDPOINT
      value: https://{{ .Values.env.service }}.{{ .Values.env.namespace.field }}/map_iam_roles_to_pod_sa
    - name: AWS_DEFAULT_REGION
      value: {{.Values.env.aws_default_region | default .Values.env.aws_region }}
    - name: AWS_REGION
      value: {{ required "Please set the AWS region that Domino is deployed to in your values file" .Values.env.aws_region}}
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: {{.Values.env.aws_sts_regional_endpoints}}
    - name: OIDC_PROVIDER
      value: {{ required "Please configure the OIDC provider URL" .Values.env.oidc_provider }}
    - name: OIDC_PROVIDER_AUDIENCE
      value: {{.Values.env.oidc_provider_audience}}
    - name: DOMINO_IRSA_PROXY
      value: http://localhost:6003

{{- end }}
