apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.env.name }}
  namespace: {{ .Values.env.namespace.field }}
  annotations:
    eks.amazonaws.com/role-arn: arn:{{ if .Values.env.govcloud }}aws-us-gov{{ else }}aws{{ end }}:iam::{{ required "Please provide the AWS account number for the account that Domino is deployed to in your values file." .Values.env.eks_aws_account }}:role/{{ required "Please provide the IAM role name for the IRSA service role in your values file." .Values.env.eks_service_role_name }}