apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.env.name }}
  namespace: {{ .Values.env.namespace.field }}
  annotations:
    eks.amazonaws.com/role-arn: arn:{{ if .Values.env.govcloud }}aws-us-gov{{ else }}aws{{ end }}:iam::{{ .Values.env.eks_aws_account }}:role/{{ .Values.env.eks_service_role_name }}