apiVersion: apps.dominodatalab.com/v1alpha1
kind: Mutation
metadata:
  name: 500-{{ .Values.env.name }}
  namespace: {{.Values.env.namespace.platform}}
rules:
- labelSelectors:
  - "dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)"
  - "app.kubernetes.io/component in (head)"
  insertContainer:
    containerType: app
    spec:
      image: "{{ .Values.image.repository }}/{{ .Values.image.clientContainer }}:{{ .Values.image.clientAppVersion }}"
      name: aws-config-file-generator
      imagePullPolicy: Always

- labelSelectors:
  - "dominodatalab.com/workload-type in (Workspace,Batch,Scheduled)"
  - "mlflow-client in (true)"
  insertContainer:
    containerType: app
    spec:
      image: "{{ .Values.image.repository }}/{{ .Values.image.clientContainer }}:{{ .Values.image.clientAppVersion }}"
      name: aws-config-file-generator
      imagePullPolicy: Always
      app:
        kubernetes:
          io/component: