image:
  repository: quay.io/domino
  serverContainer: irsa
  clientContainer: irsa-client
  serverAppVersion: v1.5.0-release
  clientAppVersion: v1.5.0-release
  pullPolicy: Always
  
env:
  name: irsa
  service: irsa-svc
  eks_aws_account: '<ACCT>'
  assets_aws_account: '<ACCT>'
  eks_service_role_name: sw-domino-irsa-svc-role
  oidc_provider: oidc.eks.us-west-2.amazonaws.com/id/<OIDC>
  oidc_provider_audience: sts.amazonaws.com
  aws_default_region: us-west-2
  aws_region: us-west-2
  aws_sts_regional_endpoints: regional
  govcloud: false
  namespace:
    platform: domino-platform
    compute: domino-compute
    field: domino-field
istio:
  enabled: false
irsa_client_sidecar:
  enabled: false